// <auto-generated />
using System;
using App.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220910040324_InitLogTables")]
    partial class InitLogTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("App.Domain.Entities.Core.ApiAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Account")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("操作人員帳號");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()")
                        .HasComment("建立日期");

                    b.Property<string>("Creator")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasComment("建立人員");

                    b.Property<Guid?>("HandledId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ApiHandledId");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasComment("請求 Method");

                    b.Property<DateTime?>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()")
                        .HasComment("最後修改日期");

                    b.Property<string>("Modifier")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasComment("最後修改人員");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("操作人員姓名");

                    b.Property<string>("RequestBody")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("請求資料");

                    b.Property<string>("RequestHeaders")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("請求網址 headers");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)")
                        .HasComment("請求網址路徑");

                    b.Property<string>("RequestQueryString")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("請求網址參數");

                    b.Property<string>("ResponseBody")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("回應資料");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("int")
                        .HasComment("回傳 http 狀態碼");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)")
                        .HasComment("RowVersion");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasComment("來源 IP");

                    b.Property<long>("TimeElapsed")
                        .HasColumnType("bigint")
                        .HasComment("執行時間(ms)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "Creator", "HandledId");

                    b.HasIndex("HandledId", "Account", "Name", "HttpMethod", "SourceIp", "RequestPath", "ResponseStatusCode");

                    b.ToTable("ApiAuditLog");

                    b.HasComment("API 系統操作紀錄");
                });

            modelBuilder.Entity("App.Domain.Entities.Core.ExceptionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()")
                        .HasComment("建立日期");

                    b.Property<string>("Creator")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasComment("建立人員");

                    b.Property<string>("ExtraData")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("ExtraData");

                    b.Property<Guid?>("HandledId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("ApiHandledId");

                    b.Property<string>("MachineName")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasComment("MachineName");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("Message");

                    b.Property<DateTime?>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()")
                        .HasComment("最後修改日期");

                    b.Property<string>("Modifier")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasComment("最後修改人員");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)")
                        .HasComment("RowVersion");

                    b.Property<string>("Source")
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("Source");

                    b.Property<string>("StackTrace")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("StackTrace");

                    b.HasKey("Id");

                    b.HasIndex("MachineName");

                    b.HasIndex("CreatedAt", "Creator", "HandledId");

                    b.ToTable("ExceptionLog");

                    b.HasComment("AP 錯誤紀錄");
                });
#pragma warning restore 612, 618
        }
    }
}
