export enum SystemConfig {
  CountryCode = "CountryCode",
  CityCode = "CityCode",
  Zip = "Zip",
  ChurchNameList = "ChurchNameList",
  EduType = "EduType",
  CareType = "CareType",
  MinistryDefStatus = "MinistryDefStatus",
  MinistryStatus = "MinistryStatus",
  IsYN = "IsYN",
  BaptizedType = "BaptizedType",
  GenderType = "GenderType",
  ClassType = "ClassType",
  QuestionnaireDetailType = "QuestionnaireDetailType",
  PaymentType = "PaymentType",
  OrderStatus = "OrderStatus",
  OrderPayStatus = "OrderPayStatus",
  JobType = "JobType",
  JoinDate = "JoinDate",
  OrgStatus = "OrgStatus",
}
